
<div class="table-container" style="max-height: 80vh; width: 100%; overflow-x: auto; overflow-y: auto;">
    <table id="task-table" class="min-w-full table-auto task-table bg-white dark:bg-gray-800">
        <thead>
            <tr id="dynamic-headers"></tr>
            </thead>
        <tbody>
            <!-- Las filas se rellenarán dinámicamente -->
        </tbody>
    </table>
</div>



<div class="pagination-container" id="pagination-controls">
    <ul id="pagination" class="pagination">
        <!-- Pagination buttons will be dynamically generated by JS -->
    </ul>
</div>



<!-- Panel de horas -->
<div class="hours-summary-main professional-hours-panel">
    <div class="hours-item">
        <strong>Total horas previstas:</strong> <span id="total-tiempo-previsto">0</span>
    </div>
    <div class="hours-item">
        <strong>Total horas reales:</strong> <span id="total-tiempo-real">0</span>
    </div>
</div>


<!-- Modal para las tareas detalladas -->
<div id="task-detail-modal" class="task-detail-modal" style="display: none;">
    <div class="task-detail-modal-content" id="task-detail-modal-content">
        <!-- El contenido del modal será insertado aquí -->
    </div>
    <button id="close-task-detail-modal" class="btn-close-task-detail-modal">Guardar</button>
</div>